---
- name: Add InfluxData repository file [RHEL/CentOS]
  template:
    src: etc/yum.repos.d/influxdata.repo.j2
    dest: /etc/yum.repos.d/influxdata.repo
    force: true
    backup: true
    mode: 0644
  when: telegraf_install_url is not defined or telegraf_install_url == None

# https://www.influxdata.com/blog/linux-package-signing-key-rotation/
- name: Add updated influxdb repo key
  ansible.builtin.rpm_key:
    key: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present

- name: Install Telegraf packages [RHEL/CentOS]
  yum:
    name: telegraf
    state: present
    update_cache: true
  when: telegraf_install_url is not defined or telegraf_install_url == None

- name: Install Telegraf from URL [RHEL/CentOS]
  yum:
    name: "{{ telegraf_install_url }}"
    state: present
  when: telegraf_install_url is defined and telegraf_install_url != None
