---
- import_tasks: install.yml
  tags: [telegraf, install]

- import_tasks: configure.yml
  tags: [telegraf, configure]

- import_tasks: start.yml
  tags: [telegraf, start]
  when: telegraf_start_service
